stages:
  - deploy

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - master
  script:
    - apt-get -u update 
    - apt-get -y install zip unzip curl
    - export xx=`cat version.txt`
    - echo $FTPSITE/janban.zip 
    - curl -O $FTPSITE/janban.zip  --user $FTPUSER:$FTPPWD
    - mv janban.zip janban.$xx.zip
    - curl -T janban.$xx.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - rm janban.$xx.zip
    - sed -i "s|#WHATSNEW#|$WHATSNEW|" js/app.js
    - sed -i "s|#VERSION#|$VERSION|" js/app.js
    - sed -i "s|#DOWNLOAD#|$DOWNLOAD|" js/app.js
    - sed -i "s|#PINGBACK#|$PINGBACK|" js/app.js
    - sed 's/";//g' js/version.js > version.txt1
    - sed 's/const VERSION = "//g' version.txt1 > version.txt
    - curl -T version.txt $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T whatsnew.html $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T upgrade.html $FTPSITE --user $FTPUSER:$FTPPWD
    - rm version.txt
    - rm version.txt1
    - rm whatsnew.html
    - rm upgrade.html
    - zip -r  janban.zip *
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
