stages:
  - deploy

deploy:
  stage: deploy
  image: debian/jessie
  only:
    - master
    - develop
  script:
    - apt-get -y install zip unzip curl
    - zip -r  janban.zip *
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T version $FTPSITE --user $FTPUSER:$FTPPWD
