# before_script:
#   - apt-get install -y zip

zip:
  script:
    - tar --exclude=".git*" --exclude="janban.tar.gz"  -zvcf janban.tar.gz *
    - curl -T janban.tar.gz ftp://ftp.janware.nl --user gitlab@janware.nl:Q1Y2iCsJyIfCk1aCua
  artifacts:
    paths: 
    - janban.tar.gz
    expire_in: 1 week
