stages:
  - version
  - deploy

version:
  stage: version
  only:
    - master
    - develop
    - release-1.0.1
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.20.0
  script:
    - release next-version --allow-current > .next-version
    - release changelog
    - release commit-and-tag CHANGELOG.md release_info
  artifacts:
    paths:
    - .next-version
  except:
    - tags

deploy:
  stage: deploy
  only:
    - master
    - develop
    - release-1.0.1
  script:
    - RELEASE_VERSION=$(<.next-version)
    - tar --exclude=".git*" --exclude="janban.tar.gz"  -zvcf janban.tar.gz *
    - curl -T janban.tar.gz $FTPSITE --user $FTPUSER:$FTPPWD
    - echo "RELEASE_VERSION=$(<.next-version)" >> version
    - curl -T version $FTPSITE --user $FTPUSER:$FTPPWD
  artifacts:
    paths: 
    - janban.tar.gz
    expire_in: 1 week
