stages:
  - deploy

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - master
  script:
    - apt-get -u update 
    - apt-get -y install zip unzip curl
    - sed -i 's/#WHATSNEW#/'"$WHATSNEW"'/' js/app.1.js
    - zip -r  janban.zip *
    - sed 's/";//g' js/version.js > version.txt1
    - sed 's/const VERSION = "//g' version.txt1 > version.txt
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T version.txt $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T whatsnew.html $FTPSITE --user $FTPUSER:$FTPPWD