# before_script:
#   - apt-get install -y zip

zip:
  script:
    - tar --exclude=".git*" --exclude="janban.tar.gz"  -zvcf janban.tar.gz *
    - curl -T janban.tar.gz $FTPSITE --user $FTPUSER:$FTPPWD
  artifacts:
    paths: 
    - janban.tar.gz
    expire_in: 1 week
