stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu
  only:
    - master
    - develop
  script:
    # - apt-get install zip
    - zip -r janban.zip *
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T version $FTPSITE --user $FTPUSER:$FTPPWD
