before_script:
  - apt-get install -y zip

zip:
  script:
    - zip janban *.* 
  artifacts:
    paths: 
    - janban.zip
    expire_in: 1 week

# FTP-gebruikersnaam: gitlab@janware.nl / ^;y}l6;Y#Uhj
# polman@janware.nl / TheMadmansQuest
# FTP-server: ftp.van-veldhuizen.nl
# FTP & expliciete FTPS-poort:  21