stages:
  - deploy

deploy:
  stage: deploy
  image: debian:jessie
  only:
    - master
  script:
    - apt-get -u update 
    - apt-get -y install zip unzip curl
    - zip -r  janban.zip *
    - curl -T janban.zip $FTPSITE --user $FTPUSER:$FTPPWD
    - curl -T version.txt $FTPSITE --user $FTPUSER:$FTPPWD
