# before_script:
#   - apt-get install -y zip

zip:
  script:
    - tar -cvzf janban.tar.gz .
  artifacts:
    paths: 
    - janban.tar.gz
    expire_in: 1 week

# FTP-gebruikersnaam: gitlab@janware.nl / ^;y}l6;Y#Uhj
# polman@janware.nl / TheMadmansQuest
# FTP-server: ftp.van-veldhuizen.nl
# FTP & expliciete FTPS-poort:  21